name: CI

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libcairo2-dev libsdl2-dev libxv-dev libxrandr-dev libao-dev libopenal-dev libudev-dev
    - name: Build
      run: make -j $(nproc) -C bsnes
    - name: Prepare artifacts
      run: |
        cp -R pack bsnes/out/
        cp README.md bsnes/out/pack/readme.md
        cp bsnes/out/bsnes bsnes/out/pack/bsnes_hd
        chmod +x bsnes/out/pack/bsnes_hd
        mkdir bsnes/out/tar
        cd bsnes/out/pack
        tar -jcvpf ../tar/bsnes_hd_beta_X_linux.tar.bz2 *
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: UNPACK-LINUX
        path: bsnes/out/tar
        if-no-files-found: error

  Linux-libretro:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential libgtk2.0-dev libpulse-dev mesa-common-dev libcairo2-dev libsdl2-dev libxv-dev libxrandr-dev libao-dev libopenal-dev libudev-dev
    - name: Build
      run: make -j $(nproc) -C bsnes target=libretro
    - name: Prepare artifacts
      run: |
        mkdir bsnes/out/pack
        cp README.md bsnes/out/pack
        cp LICENSE bsnes/out/pack
        cp -R bsnes/out/*bsnes* bsnes/out/pack
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bsnes_hd_beta_X_linux_libretro
        path: bsnes/out/pack
        if-no-files-found: error
